### ISSUE TITLE
which python version should I use?

### ISSUE THREAD

**Issue by exitNA** [aws-robotics/aws-robomaker-sample-application-deepracer#10]
the ROS kinetic need python 2, but colcon use python 3.5, when install ros using 
sudo apt install -y ros-kinetic-desktop-full
it is using python 2,
but when install colcon it is using python 3,
so, which python should I use?

**Comment by x77a1** [comment]
@exitNA You would need both Python 2 and Python 3. Please reopen the issue incase you are facing any issue with this setup.
