### ISSUE TITLE
No simulation jobs in AWS RoboMaker

### ISSUE THREAD

**Issue by madan96** [aws-robotics/aws-robomaker-sample-application-deepracer#27]
Hi, I'm using the `local_training.launch` to train the bot over the hard track. I can see the immediate rewards being outputted on the terminal. The checkpoints are also getting saved in the S3 bucket. I followed the README to check for the reward graph, but I couldn't find any simulation jobs inside the RoboMaker. I saw that there's a `send_reward_to_cloudwatch` method inside deepracer env for this purpose. Any possible reasons why it isn't working for me as intended?

**Comment by raghaprasad** [comment]
Hi @madan96 , Can you provide a few more details including information about your training environment? Are you using RoboMaker or https://aws.amazon.com/deepracer/ ?
In either case if you can provide some information about session ids and such. It would be helpful to for us to investigate further.

**Comment by nburek** [comment]
I'm closing this issue as there is not enough information for us to debug at the moment. Please feel free to open it again if you are still experiencing problems. If you do reopen, it we will need more information about what method you are using to launch the simulation (ie. using roslaunch, the deepracer console, uploading a bundle to robomaker, etc). It would also be helpful if you can reference which README document and which section of that document you are following.
