### ISSUE TITLE
No training with Gazebo

### ISSUE THREAD

**Issue by realleyriley** [aws-robotics/aws-robomaker-sample-application-deepracer#37]
Hello, 

When I first ran `roslaunch deepracer_simulation local_training.launch` gazebo did not launch but the model started training and I could see the model.pd as well as log files in my S3 bucket. 

Since Gazebo was not launching, I fixed it by doing this0: https://forums.aws.amazon.com/thread.jspa?messageID=915537&#915537

Now Gazebo successfully launches, but the model does not train. The car does not move and the terminal output is stuck at "Saved TF frozen graph!"
![image](https://user-images.githubusercontent.com/43195764/64669554-dcc86380-d416-11e9-9b97-740676cf97df.png)

So I need it to train and I'd like to be able to see it train, just like how it does in the deepracer console through AWS.

**Comment by timrobotson** [comment]
I'm trying this out now to see what could be going on. What version of ROS and Gazebo are you running this with and what version of Ubuntu are you using? 

Instead of changing the launch file you can make the gazebo viewer launch by adding `gui:=true` to your launch command (so the full command woudl be `roslaunch deepracer_simulation local_training.launch gui:=true`), that's the general way of setting ros `<arg>` values at launch time. 

Regards, Tim

**Comment by realleyriley** [comment]
I'm on Ubuntu 16.04.6 LTS with ROS kinetic and Gazebo 7.0. 

So I redownloaded the repository and built and bundled with colcon, then tried `roslaunch deepracer_simulation local_training.launch` but gazebo crashed. I quit the process and then tried again and gazebo launched, and the terminal is stuck at Saved TF Graph.

I can give you any log files you want as well. Thank you for looking into it. Are you able to reproduce the error?

**Comment by realleyriley** [comment]
So even though it was stuck at "Saved TF frozen graph!", the CPU was still being utilized (at like 70%) so I let it run overnight. There has been some output to the terminal but it looks like its in a loop that breaks or something 
![image](https://user-images.githubusercontent.com/43195764/64809326-e9030c80-d54d-11e9-9338-923462baef73.png)

**Comment by timrobotson** [comment]
Could it be that it's actually running just not outputting any logs? Is the car moving in simulation at all? Is it being reset back to the start of the track often?

**Comment by realleyriley** [comment]
Right now, in the simulation I cannot see the car moving. After I let it run overnight and saw it the next morning it was in a different place as you can see in the screenshot, so it must've moved somehow but I'm guessing its a glitch. In the past I have seen the car slowly move (not drive) across the track as soon as it spawned which was clearly glitching.
I'll try reinstalling Ubuntu and ROS. Is there any specific version I should get within Kinetic this time? Or maybe a specific version of Ubuntu?

**Comment by realleyriley** [comment]
Well I reinstalled Ubuntu and set everything up and its working now. This time around I didn't need to change the .gazebo files and insert `<legacyModeNS>true</legacyModeNS>`.
I just used `gui:=true` and it worked.
